name: CI
on:
  - push
  - workflow_dispatch
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Make
        run: make all
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: desumasu-convertor
          path: desumasu-convertor
